name: Python CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Run and Push
      run: |
         git config --local user.email "1141101853@qq.com"
         git config --local user.name "xiaopowanyi"
         git pull
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         python run.py
    - name: Commit files
      run: |
         git add .
         git commit -m "update files"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main